package com.incomab.model;
// Generated 08/09/2017 01:42:44 PM by Hibernate Tools 4.3.1



/**
 * TSerie generated by hbm2java
 */
public class TSerie  implements java.io.Serializable {


     private int idSerie;
     private TLocal TLocal;
     private String tipoDocumento;
     private String serieDocumento;

    public TSerie() {
    }

    public TSerie(int idSerie, TLocal TLocal, String tipoDocumento, String serieDocumento) {
       this.idSerie = idSerie;
       this.TLocal = TLocal;
       this.tipoDocumento = tipoDocumento;
       this.serieDocumento = serieDocumento;
    }
   
    public int getIdSerie() {
        return this.idSerie;
    }
    
    public void setIdSerie(int idSerie) {
        this.idSerie = idSerie;
    }
    public TLocal getTLocal() {
        return this.TLocal;
    }
    
    public void setTLocal(TLocal TLocal) {
        this.TLocal = TLocal;
    }
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public String getSerieDocumento() {
        return this.serieDocumento;
    }
    
    public void setSerieDocumento(String serieDocumento) {
        this.serieDocumento = serieDocumento;
    }




}


